language: node_js
node_js:
- "8.3"
os:
- osx
osx_image: xcode61
rvm:
- 2.2
cache:
  directories:
    - ./Unity
before_install:
- chmod a+x ./Travis/installUnity.sh
- npm install -g npm@6.x
install:
- ./Travis/installUnity.sh
- cd appscan; make asoc-tool; cd ../;
before_script:
- chmod a+x ./Travis/createProject.sh
- chmod a+x ./Travis/installSDK.sh
- chmod a+x ./Travis/runTests.sh
- chmod a+x ./Travis/build.sh
- chmod a+x ./appscan/ASOC.sh;
script:
- ./Travis/createProject.sh
- ./Travis/installSDK.sh
# - ./Travis/runTests.sh
# - ./Travis/build.sh
- ./appscan/ASOC.sh;
deploy:
  - provider: script
    skip_cleanup: true
    script: npx travis-deploy-once "npx semantic-release"
